angular.module('app.config',[])
	.constant('server', {
		baseApiUrl: window.location.origin+'/api/'
	})
	.constant('apis', {
        login: 'users/login',
		logout: 'users/logout',
		checkAuth: 'users/check/authentication',
		getProductItems: 'procurement/search/product/item',
		addProcurement: 'procurement/add/procurement',
		addToCart: 'procurement/add/cart',
		getProcureAudit:'procurement/get/procurementAudit',
		getProcurement:'procurement/get/procurement',
		updateProcurement: 'procurement/update/procurement',
		passwordReset : 'users/password/reset',
		addDepedent:'userProfile/addDependant',
		companyLogoUpload : 'admin/upload/company/logo',
		companyLoginLogoUpload : 'admin/upload/companylogin/logo',
		loginBannerImageUpload : 'admin/upload/banner/image',
		saveSettings : 'setting/save',
		getPluginSettings : 'setting/getPlugins',
		plugins : 'admin/plugins',
		getManagers: 'admin/getManager',
		getRoles : 'admin/all/roles',
		createEmailSetting : 'admin/emailSetting/save',
		getHotelProject:'hotel/allProjects',
		hotelLogoUploadWithData:'hotel/projects/save',
		getHotelActualData :'hotel/dataEntryFields',
		getHotelActualView : 'hotel/actual/view',
		getProjectMaster:'hotel/projects/datafields',
		getHotelBudget : 'hotel/budget',
		getUserProjectList : 'hotel/userProjects',
		getHotelCashflow: 'hotel/cashflow',
		savePeriod:'hotel/period/save',
		getHotelProjectWithPeriod : 'hotel/period',
		saveHotelBudget : 'hotel/budget/save',
		saveHotelCashflow : 'hotel/cashflow/save',
		getHotelActual : 'hotel/actual',
		saveHotelActual : 'hotel/actual/save',
		getHotelForecast : 'hotel/forecast',
		saveHotelForecast : 'hotel/forecast/save',
		getUnlockBudget : 'hotel/budget/lock',
		getUnlockActual : 'hotel/actual/lock',
		saveUnlockBudget : 'hotel/budget/unlock',
		saveUnlockActual : 'hotel/actual/unlock',
		createUser : 'admin/user/save',
		getDashboardRevenueData : 'hotel/dashboard/revenue',
		getDashboardOccupanyData : 'hotel/dashboard/occupany',
		getDashboardScopeRevData : 'hotel/dashboard/scopeRevenue',
		getHotelPNL : 'hotel/PNL',
		getHotelDashProjectWithPeriod : 'hotel/dashboard/period',
		saveHotelPNL : 'hotel/PNL/save'
	});